[package]
name = "sendgrid-amqp-bridge"
version = "0.1.0"
authors = ["Otavio Salvador <otavio@ossystems.com.br>"]
license = "MIT"
edition = "2018"

[dependencies]
exitfailure = "0.5"
failure = "0.1"
futures = "0.1"
lapin = { version = "0.15", package = "lapin-futures" }
serde = { version = "1", features = ["std", "derive"] }
serde_json = "1"
serde_with = "0.2"
serde_yaml = "0.8"
slog = { version = "2", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = "2"
slog-term = "2"
structopt = "0.2"
tokio = "0.1"

[build-dependencies]
git-version = "0.2"
