amqp:
  dsn: amqp://guest:guest@127.0.0.1:5672
  exchange_name: email
  routing_key: email_key
  queue_name: send_email

sendgrid:
  api_key: API Key
  sender_name: Sender name
  sender_email: sender@email.com
  email_templates:
    template_name1:
      template_id: d-9b...
      required_fields:
        - field1
        - field2
        - field3
    template_name2:
      template_id: d-9c...
